### ISSUE TITLE
Merge OutboxStorageStrategy with StorageStrategy

### ISSUE THREAD

**Issue by lzukowski** [Enforcer/python-event-sourcery#20] opened 2023-07-27 18:40 UTC

**Comment by Enforcer** [comment] 2023-08-05 10:28
Did you mean "merge"?

**Comment by Enforcer** [comment] 2023-09-09 17:21
Duplicate of https://github.com/Enforcer/python-event-sourcery/issues/24

**Closed by Enforcer** 2023-09-09 17:21 UTC
